config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  devise_for :users
  

  resources :feedbacks
  resources :reviews
  resources :online_bookings
  resources :bookings
  resources :movies
  resources :screens
  resources :veereshes

end

app/models/online_booking.rb
class OnlineBooking < ActiveRecord::Base

	belongs_to :movie
	belongs_to :booking
	
end

app/controllers/online_bookings_controller.rb
class OnlineBookingsController < ApplicationController
  before_action :set_online_booking, only: [:show, :edit, :update, :destroy]

  # GET /online_bookings
  # GET /online_bookings.json
  def index
    @online_bookings = OnlineBooking.all
  end

  # GET /online_bookings/1
  # GET /online_bookings/1.json
  def show
  end

  # GET /online_bookings/new
  def new
    @online_booking = OnlineBooking.new
  end

  # GET /online_bookings/1/edit
  def edit
  end

  # POST /online_bookings
  # POST /online_bookings.json
  def create
    @online_booking = OnlineBooking.new(online_booking_params)

    respond_to do |format|
      if @online_booking.save
        format.html { redirect_to @online_booking, notice: 'Online booking was successfully created.' }
        format.json { render :show, status: :created, location: @online_booking }
      else
        format.html { render :new }
        format.json { render json: @online_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /online_bookings/1
  # PATCH/PUT /online_bookings/1.json
  def update
    respond_to do |format|
      if @online_booking.update(online_booking_params)
        format.html { redirect_to @online_booking, notice: 'Online booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @online_booking }
      else
        format.html { render :edit }
        format.json { render json: @online_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /online_bookings/1
  # DELETE /online_bookings/1.json
  def destroy
    @online_booking.destroy
    respond_to do |format|
      format.html { redirect_to online_bookings_url, notice: 'Online booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_online_booking
      @online_booking = OnlineBooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def online_booking_params
      params.require(:online_booking).permit(:movie_id, :booking_id)
    end
end

app/helpers/online_bookings_helper.rb
module OnlineBookingsHelper
end

app/views/online_bookings/_form.html.erb
<%= form_for(@online_booking) do |f| %>
  <% if @online_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@online_booking.errors.count, "error") %> prohibited this online_booking from being saved:</h2>

      <ul>
      <% @online_booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.number_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :booking_id %><br>
    <%= f.number_field :booking_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/online_bookings/edit.html.erb
<h1>Editing Online Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @online_booking %> |
<%= link_to 'Back', online_bookings_path %>

app/views/online_bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Online Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Booking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @online_bookings.each do |online_booking| %>
      <tr>
        <td><%= online_booking.movie_id %></td>
        <td><%= online_booking.booking_id %></td>
        <td><%= link_to 'Show', online_booking %></td>
        <td><%= link_to 'Edit', edit_online_booking_path(online_booking) %></td>
        <td><%= link_to 'Destroy', online_booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Online booking', new_online_booking_path %>

app/views/online_bookings/new.html.erb
<h1>New Online Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', online_bookings_path %>

app/views/online_bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @online_booking.movie_id %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @online_booking.booking_id %>
</p>

<%= link_to 'Edit', edit_online_booking_path(@online_booking) %> |
<%= link_to 'Back', online_bookings_path %>