config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  devise_for :users
  

  resources :feedbacks
  resources :reviews
  resources :online_bookings
  resources :bookings
  resources :movies
  resources :screens
  resources :veereshes

end

app/models/screen.rb
class Screen < ActiveRecord::Base

	has_many :movies
	belongs_to :veeresh
	
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  before_action :set_screen, only: [:show, :edit, :update, :destroy]

  # GET /screens
  # GET /screens.json
  def index
    @screens = Screen.all
  end

  # GET /screens/1
  # GET /screens/1.json
  def show
  end

  # GET /screens/new
  def new
    @screen = Screen.new
  end

  # GET /screens/1/edit
  def edit
  end

  # POST /screens
  # POST /screens.json
  def create
    @screen = Screen.new(screen_params)

    respond_to do |format|
      if @screen.save
        format.html { redirect_to @screen, notice: 'Screen was successfully created.' }
        format.json { render :show, status: :created, location: @screen }
      else
        format.html { render :new }
        format.json { render json: @screen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screens/1
  # PATCH/PUT /screens/1.json
  def update
    respond_to do |format|
      if @screen.update(screen_params)
        format.html { redirect_to @screen, notice: 'Screen was successfully updated.' }
        format.json { render :show, status: :ok, location: @screen }
      else
        format.html { render :edit }
        format.json { render json: @screen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screens/1
  # DELETE /screens/1.json
  def destroy
    @screen.destroy
    respond_to do |format|
      format.html { redirect_to screens_url, notice: 'Screen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screen
      @screen = Screen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screen_params
      params.require(:screen).permit(:name, :capacity)
    end
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/views/screens/_form.html.erb
<%= form_for(@screen) do |f| %>
  <% if @screen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screen.errors.count, "error") %> prohibited this screen from being saved:</h2>

      <ul>
      <% @screen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.text_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screens/edit.html.erb
<h1>Editing Screen</h1>

<%= render 'form' %>

<%= link_to 'Show', @screen %> |
<%= link_to 'Back', screens_path %>

app/views/screens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Screens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screens.each do |screen| %>
      <tr>
        <td><%= screen.name %></td>
        <td><%= screen.capacity %></td>
        <td><%= link_to 'Show', screen %></td>
        <td><%= link_to 'Edit', edit_screen_path(screen) %></td>
        <td><%= link_to 'Destroy', screen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Screen', new_screen_path %>

app/views/screens/new.html.erb
<h1>New Screen</h1>

<%= render 'form' %>

<%= link_to 'Back', screens_path %>

app/views/screens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @screen.name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @screen.capacity %>
</p>

<%= link_to 'Edit', edit_screen_path(@screen) %> |
<%= link_to 'Back', screens_path %>