config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  devise_for :users
  

  resources :feedbacks
  resources :reviews
  resources :online_bookings
  resources :bookings
  resources :movies
  resources :screens
  resources :veereshes

end

app/models/veeresh.rb
class Veeresh < ActiveRecord::Base

	has_many :users
	has_many :screens
end

app/controllers/veereshes_controller.rb
class VeereshesController < ApplicationController
  before_action :set_veeresh, only: [:show, :edit, :update, :destroy]

  # GET /veereshes
  # GET /veereshes.json
  def index
    @veereshes = Veeresh.all
  end

  # GET /veereshes/1
  # GET /veereshes/1.json
  def show
  end

  # GET /veereshes/new
  def new
    @veeresh = Veeresh.new
  end

  # GET /veereshes/1/edit
  def edit
  end

  # POST /veereshes
  # POST /veereshes.json
  def create
    @veeresh = Veeresh.new(veeresh_params)

    respond_to do |format|
      if @veeresh.save
        format.html { redirect_to @veeresh, notice: 'Veeresh was successfully created.' }
        format.json { render :show, status: :created, location: @veeresh }
      else
        format.html { render :new }
        format.json { render json: @veeresh.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veereshes/1
  # PATCH/PUT /veereshes/1.json
  def update
    respond_to do |format|
      if @veeresh.update(veeresh_params)
        format.html { redirect_to @veeresh, notice: 'Veeresh was successfully updated.' }
        format.json { render :show, status: :ok, location: @veeresh }
      else
        format.html { render :edit }
        format.json { render json: @veeresh.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veereshes/1
  # DELETE /veereshes/1.json
  def destroy
    @veeresh.destroy
    respond_to do |format|
      format.html { redirect_to veereshes_url, notice: 'Veeresh was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veeresh
      @veeresh = Veeresh.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veeresh_params
      params.require(:veeresh).permit(:establishment, :image, :canteen, :proprietor, :seating_capacity, :car_parks, :number_of_tickets_online, :number_of_tickets_box, :total_amount_per_day, :screen_id, :booking_id, :feedback_id, :user_id)
    end
end

app/helpers/veereshes_helper.rb
module VeereshesHelper
end

app/views/veereshes/_form.html.erb
<%= form_for(@veeresh) do |f| %>
  <% if @veeresh.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@veeresh.errors.count, "error") %> prohibited this veeresh from being saved:</h2>

      <ul>
      <% @veeresh.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :establishment %><br>
    <%= f.text_field :establishment %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :canteen %><br>
    <%= f.text_field :canteen %>
  </div>
  <div class="field">
    <%= f.label :proprietor %><br>
    <%= f.text_field :proprietor %>
  </div>
  <div class="field">
    <%= f.label :seating_capacity %><br>
    <%= f.text_field :seating_capacity %>
  </div>
  <div class="field">
    <%= f.label :car_parks %><br>
    <%= f.text_field :car_parks %>
  </div>
  <div class="field">
    <%= f.label :number_of_tickets_online %><br>
    <%= f.number_field :number_of_tickets_online %>
  </div>
  <div class="field">
    <%= f.label :number_of_tickets_box %><br>
    <%= f.number_field :number_of_tickets_box %>
  </div>
  <div class="field">
    <%= f.label :total_amount_per_day %><br>
    <%= f.text_field :total_amount_per_day %>
  </div>
  <div class="field">
    <%= f.label :screen_id %><br>
    <%= f.number_field :screen_id %>
  </div>
  <div class="field">
    <%= f.label :booking_id %><br>
    <%= f.number_field :booking_id %>
  </div>
  <div class="field">
    <%= f.label :feedback_id %><br>
    <%= f.number_field :feedback_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/veereshes/edit.html.erb
<h1>Editing Veeresh</h1>

<%= render 'form' %>

<%= link_to 'Show', @veeresh %> |
<%= link_to 'Back', veereshes_path %>

app/views/veereshes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Veereshes</h1>

<table>
  <thead>
    <tr>
      <th>Establishment</th>
      <th>Image</th>
      <th>Canteen</th>
      <th>Proprietor</th>
      <th>Seating capacity</th>
      <th>Car parks</th>
      <th>Number of tickets online</th>
      <th>Number of tickets box</th>
      <th>Total amount per day</th>
      <th>Screen</th>
      <th>Booking</th>
      <th>Feedback</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veereshes.each do |veeresh| %>
      <tr>
        <td><%= veeresh.establishment %></td>
        <td><%= veeresh.image %></td>
        <td><%= veeresh.canteen %></td>
        <td><%= veeresh.proprietor %></td>
        <td><%= veeresh.seating_capacity %></td>
        <td><%= veeresh.car_parks %></td>
        <td><%= veeresh.number_of_tickets_online %></td>
        <td><%= veeresh.number_of_tickets_box %></td>
        <td><%= veeresh.total_amount_per_day %></td>
        <td><%= veeresh.screen_id %></td>
        <td><%= veeresh.booking_id %></td>
        <td><%= veeresh.feedback_id %></td>
        <td><%= veeresh.user_id %></td>
        <td><%= link_to 'Show', veeresh %></td>
        <td><%= link_to 'Edit', edit_veeresh_path(veeresh) %></td>
        <td><%= link_to 'Destroy', veeresh, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veeresh', new_veeresh_path %>

app/views/veereshes/new.html.erb
<h1>New Veeresh</h1>

<%= render 'form' %>

<%= link_to 'Back', veereshes_path %>

app/views/veereshes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Establishment:</strong>
  <%= @veeresh.establishment %>
</p>

<p>
  <strong>Image:</strong>
  <%= @veeresh.image %>
</p>

<p>
  <strong>Canteen:</strong>
  <%= @veeresh.canteen %>
</p>

<p>
  <strong>Proprietor:</strong>
  <%= @veeresh.proprietor %>
</p>

<p>
  <strong>Seating capacity:</strong>
  <%= @veeresh.seating_capacity %>
</p>

<p>
  <strong>Car parks:</strong>
  <%= @veeresh.car_parks %>
</p>

<p>
  <strong>Number of tickets online:</strong>
  <%= @veeresh.number_of_tickets_online %>
</p>

<p>
  <strong>Number of tickets box:</strong>
  <%= @veeresh.number_of_tickets_box %>
</p>

<p>
  <strong>Total amount per day:</strong>
  <%= @veeresh.total_amount_per_day %>
</p>

<p>
  <strong>Screen:</strong>
  <%= @veeresh.screen_id %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @veeresh.booking_id %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @veeresh.feedback_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @veeresh.user_id %>
</p>

<%= link_to 'Edit', edit_veeresh_path(@veeresh) %> |
<%= link_to 'Back', veereshes_path %>